### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by knminhaz** [fawazahmed0/quran-api#24]
This is not an issue. But I cant figure out how to use your API. Any documentation?

**Comment by fawazahmed0** [comment]
Documentation for API is [here](https://github.com/fawazahmed0/quran-api#readme)
Here is all the editions:
https://cdn.jsdelivr.net/gh/fawazahmed0/quran-api@1/editions.json
Accessing `aar_sheikhmahmoudab` edition:
https://cdn.jsdelivr.net/gh/fawazahmed0/quran-api@1/editions/aar-sheikhmahmoudab.json

**Comment by fawazahmed0** [comment]
You can also download the data in this format:
https://raw.githubusercontent.com/fawazahmed0/quran-api/1/database/chapterverse/eng-abdelhaleem.txt

https://github.com/fawazahmed0/quran-api/tree/1/database/chapterverse
