### ISSUE TITLE
remove duplicated translations

### ISSUE THREAD

**Issue by fawazahmed0** [fawazahmed0/quran-api#30]
maybe checking using elastic search or something

**Comment by njmulsqb** [comment]
Can you please elaborate the issue a bit more, I might take this! @fawazahmed0

**Comment by fawazahmed0** [comment]
The [editions](https://cdn.jsdelivr.net/gh/fawazahmed0/quran-api@1/editions.json) has few duplicates(i.e same translation is stored in multiple editions ).
For example [deu-asfbubenheimand](https://cdn.jsdelivr.net/gh/fawazahmed0/quran-api@1/editions/deu-asfbubenheimand.json) is duplicate of [deu-frankbubenheima](https://cdn.jsdelivr.net/gh/fawazahmed0/quran-api@1/editions/deu-frankbubenheima.json) . 
If you can give me a list of all dupilcates, that should help. 
I will remove the duplicates and keeping only one original copy

**Comment by Shahzadworld** [comment]
> The [editions](https://cdn.jsdelivr.net/gh/fawazahmed0/quran-api@1/editions.json) has few duplicates(i.e same translation is stored in multiple editions ).
> For example [deu-asfbubenheimand](https://cdn.jsdelivr.net/gh/fawazahmed0/quran-api@1/editions/deu-asfbubenheimand.json) is duplicate of [deu-frankbubenheima](https://cdn.jsdelivr.net/gh/fawazahmed0/quran-api@1/editions/deu-frankbubenheima.json) . 
> If you can give me a list of all dupilcates, that should help. 
> I will remove the duplicates and keeping only one original copy

Assalamualaikum friends, I hope you are doing well.
My name is Mohammad Shahzad, I am 20 years old.
I have spent the last two years composing the complete translation and interpretation of the Holy Quran in MS Word.
Now I wish to include it in the "API" of Quran.
I want to add it with another script.
I have no knowledge of coding.
But if someone guides me, I can work hard.

Please friends help me in this good work.
JzakAllah

**Comment by jazimabbas** [comment]
I have a question. Please help me out. I can see all the text is stored in this github repository. There is no external database or external file system where you are putting all "Quran" text. How is this working.
Thanks in advance.

**Comment by jazimabbas** [comment]
Please guide me. I want to contribute to this project.

**Comment by fawazahmed0** [comment]
> I can see all the text is stored in this github repository.

Yes, all the api files are stored in this repo, and these files are served using [jsdelivr](https://www.jsdelivr.com/)

**Comment by fawazahmed0** [comment]
Removing the duplicated translations may introduce breaking changes for others. So it might be better not to remove duplicated translations.
