### ISSUE TITLE
No surah's in API

### ISSUE THREAD

**Issue by fawazahmed0** [fawazahmed0/quran-api#31]
Assala-mu-alai-kum brother .How are you ? Actually, brother, I am new to a flutter, recently I finished the flutter course, so I am trying to practice building an AL-Quran Mobile Apps, That's why I am trying to use your API,In this API I don't find any surah, Just found sura list. So if you can give me the actual API where I can find the ALL Surah and I can complete this project, That would be very helpful for me.
Thank you!

**Comment by fawazahmed0** [comment]
@ismailhossainmaruf waleikum salam brother, I have copied your comment here, lets chat here.

This API is structured into editions(or translations)
So if you want to get list of all translations:
https://cdn.jsdelivr.net/gh/fawazahmed0/quran-api@1/editions.json

In below link, I am fetching complete bengali quran translation by muhiddin khan 
https://cdn.jsdelivr.net/gh/fawazahmed0/quran-api@1/editions/ben-muhiuddinkhan.json

Similarly for complete english quran translation by Abdel Haleem
https://cdn.jsdelivr.net/gh/fawazahmed0/quran-api@1/editions/eng-abdelhaleem.json

I have created a simple app, which uses this api, here is the [link to that app](https://fawazahmed0.github.io/quran/)

**Comment by ismailhossainmaruf** [comment]
Thank you, brother. I will try with this In-sha-allah.
Which API is for Arabic? Like this?

**Comment by fawazahmed0** [comment]
Here is for arabic quran:
https://cdn.jsdelivr.net/gh/fawazahmed0/quran-api@1/editions/ara-quranacademy.json

or here is one with arabic quran with explanation:
https://cdn.jsdelivr.net/gh/fawazahmed0/quran-api@1/editions/ara-sirajtafseer.json

**Comment by ismailhossainmaruf** [comment]
Thank you, I will check it out.
