### ISSUE TITLE
Wanting to understand the difference between QuranUthmaniHaf and QuranUthmaniEnc.

### ISSUE THREAD

**Issue by mohalibou** [fawazahmed0/quran-api#37]
If the author of the API could clarify the difference between Quran Uthmani Hafs and Quran Uthmani Enc, I would be most grateful.

**Comment by fawazahmed0** [comment]
Quran Uthmani Enc doesn't follow unicode standard, you need to use specific fonts for it.

Quran Uthmani Hafs follows unicode standard, you can use any unicode font

For example, see verse [2:7](https://fawazahmed0.github.io/quran/?editions=ara-quranuthmanienc%2Cara-quranuthmanihaf&chapter=2#2:7)

**Comment by Shahzadworld** [comment]
Application for translation and commentary to be added to the Quran "API".
Assalamualaikum friends, I hope you are doing well.
My name is Mohammad Shahzad, I am 20 years old.
I have spent the last two years composing the complete translation and interpretation of the Holy Quran in MS Word.
Now I wish to include it in the "API" of Quran.
I want to add it with another script.
I have no knowledge of coding.
But if someone guides me, I can work hard.

Please friends help me in this good work.
JzakAllah
