### ISSUE TITLE
Issue regarding using the uthmanic-hafs1-ver14.ttf font on ara-quranuthmanihaf.json

### ISSUE THREAD

**Issue by mohalibou** [fawazahmed0/quran-api#38]
I am attempting to use the `uthmanic-hafs1-ver14.ttf` font with the `ara-quranuthmanihaf.json` data for the Quran. 

However, there doesn't seem to be some characters that are formatting to the proper font correctly. Please see my example below.

<img width="484" alt="Screenshot 2022-12-01 at 2 18 27 PM" src="https://user-images.githubusercontent.com/73797962/205171141-7e1b4a37-4d30-4d79-b310-37184a0403b5.png">

The arrows point to unicode characters that don't follow the proper font style. Am I using the incorrect font? Is there another json file I should be using instead when using the hafs Quran?

JZK.

**Comment by fawazahmed0** [comment]
You can use any other arabic unicode font

**Extra information:**
`uthmanic-hafs1-ver14.ttf` is released by [quran complex](https://qurancomplex.gov.sa/). But it was not following proper unicode standards. I modified few things in those fonts to follow unicode standards. This modification caused improper positioning of few characters.

**Comment by mohalibou** [comment]
I'm confused. 

You claimed to modify the `uthmanic-hafs1-ver14.ttf` font to fit unicode standards. `ara-quranuthmanihaf.json` already follows the unicode standard.

Therefore, shouldn't the standardized font work with the standardized json properly? Am I missing something?

**Comment by fawazahmed0** [comment]
> You claimed to modify the uthmanic-hafs1-ver14.ttf font to fit unicode standards

yes

> ara-quranuthmanihaf.json already follows the unicode standard

I converted the text provided by quran complex to fit unicode standards and that's why `ara-quranuthmanihaf.json` is in unicode standard.

The issue mentioned by you is a positioning issue, which is related to font. You can use any other unicode font to fix this issue.

**Comment by mohalibou** [comment]
Ah, so you modified both `uthmanic-hafs1-ver14.ttf` and `ara-quranuthmanihaf.json` to fit unicode standards?

**Comment by fawazahmed0** [comment]
> Ah, so you modified both `uthmanic-hafs1-ver14.ttf` and `ara-quranuthmanihaf.json` to fit unicode standards?
yes

**Comment by mohalibou** [comment]
Gotcha.

In that case, I have a clarifying question. In the `editions.json` file, you provide these comments with regards to using the `ara-quranuthmanihaf.json` text:

> Please use the quran complex Uthamnic fonts to view this text properly, The following characters were replaced (to open fathatan,dammatan and kasratan) to conform to unicode standard,'ٖ'(u+0656)->'ࣲ'(u+08f2),'ٗ'(u+0657)->'ࣰ'(u+08f0),'ٞ'(u+065E)->'ࣱ'(u+08f1) , Please use Quran complex Uthamnic hafs fonts with full suffix to view this text properly

When you said to "use Quran complex Uthamnic hafs fonts with full suffix," I was under the impression you were referring to the `uthmanic-hafs1-ver14.ttf` font. Is this incorrect? If so, which font is this comment referring to?

**Comment by fawazahmed0** [comment]
Yes i was referring to `uthmanic-hafs1-ver14.ttf`. But you can use any other unicode font.
For example in my windows 11, in notepad++, this is how it looks like:
![Screenshot (67)](https://user-images.githubusercontent.com/20347013/205419647-d60f8e3f-bc9b-42bf-a9de-7e8a6c54a0a3.png)

**Comment by fawazahmed0** [comment]
And this is how it looks like in arial font:
![Screenshot (68)](https://user-images.githubusercontent.com/20347013/205419709-5763c86c-b412-476e-968a-1de62fb39822.png)

**Comment by mohalibou** [comment]
Ok, so I've tried every single uthmani hafs font the API provides, and I am still running into the same problem. Please see the image below, and I will demonstrate the problem I'm having.

<img width="777" alt="Screenshot 2022-12-02 at 8 10 09 PM" src="https://user-images.githubusercontent.com/73797962/205422446-418c8f39-f278-454f-ab81-cbfd145acced.png">

I'm only showing two fonts, but I've tried seven in total, and all of them do either one of the two things I'm showing in the above image. The fonts will either show the incorrect font and not be positioned correctly, or it will show the correct font, but still not be positioned correctly. I'm sure you can notice the difference. If you want a demonstration of all the fonts, I have created a GitHub repo you can download where I try all the uthmani hafs fonts I could find.

https://github.com/mohalibou/font-issue

None of the fonts seem to give the desired result, like in the below image:

<img width="629" alt="Screenshot 2022-12-02 at 8 43 38 PM" src="https://user-images.githubusercontent.com/73797962/205424117-88530624-2c6c-456c-bef6-fb4e67884881.png">

**Comment by fawazahmed0** [comment]
All the quran complex fonts available in my api has this positioning issue. I cannot fix these issues as I am not a font developer. You can try using fonts provided by [khaledhosny](https://github.com/khaledhosny) and if you find any issue with his fonts, you can raise a issue at his repository (he should be able to fix it, as he is a font developer)

**Comment by mohalibou** [comment]
Thank you, this was the clarification I was looking for.

Are there other fonts in the API that don't have this positioning issue that you recommend?

**Comment by fawazahmed0** [comment]
> Thank you, this was the clarification I was looking for.
> 
> Are there other fonts in the API that don't have this positioning issue that you recommend?

I don't know, I haven't tested those fonts. But You can try this [website](https://fawazahmed0.github.io/test-arabic-fonts/#fontSize=30&fontBold=false&text=%D9%82%D9%8F%D9%84%D9%92%20%D9%8A%D9%8E%D8%A7%20%D8%A3%D9%8E%D9%8A%D9%91%D9%8F%D9%87%D9%8E%D8%A7%20%D8%A7%D9%84%D9%92%D9%83%D9%8E%D8%A7%D9%81%D9%90%D8%B1%D9%8F%D9%88%D9%86%D9%8E%0A%20%20%D8%AB%D9%8F%D9%85%D9%91%D9%8E%20%D9%84%D9%8E%D8%AA%D9%8E%D8%B1%D9%8E%D9%88%D9%8F%D9%86%D9%91%D9%8E%D9%87%D9%8E%D8%A7%20%D8%B9%D9%8E%D9%8A%D9%92%D9%86%D9%8E%20%D8%A7%D9%84%D9%92%D9%8A%D9%8E%D9%82%D9%90%D9%8A%D9%86%D9%90)
