### ISSUE TITLE
Translation help needed

### ISSUE THREAD

**Issue by Sheikh24608** [fawazahmed0/quran-api#39]
Assalamualaikum
I wanna know if that is possible to get translation like instead of going to editions and see which edition has the language translation I want
Actually I am making a discord bot which will fetch data through a rest API and use it as to display verse or info or maybe after this Hadith 
So I am willing if some guy write
`/get verse 1:4 en`
Where 1:4 is the ayah 4 of surah number one but I don't want help with this I wanna know if the guy writes en it will show translation in English
Or let's say "ur" (don't know exact term) it will show the verse in Urdu 
I will be really thankful
Jazak Allah

**Comment by fawazahmed0** [comment]
You can do something like this:
`https://cdn.jsdelivr.net/gh/fawazahmed0/quran-api@1/editions/{editionName}/{chapter}/{verse}.json`

For example:
verse `1:4` , language `english`, translator `Umm muhammad`:
https://cdn.jsdelivr.net/gh/fawazahmed0/quran-api@1/editions/eng-ummmuhammad/1/4.json

verse `1:4` language `Urdu`, translator `Muhammand Taqi Usmani`:
https://cdn.jsdelivr.net/gh/fawazahmed0/quran-api@1/editions/urd-muhammadtaqiusm/1/4.json

You can get list of all available editions here:
https://cdn.jsdelivr.net/gh/fawazahmed0/quran-api@1/editions.json

**Comment by Sheikh24608** [comment]
Thanks for responding
An yea thanks for help but I already did in another way  
May Allah bless you for making such a beautiful API
![Uploading q4{dbfc3cc} (2a0c077c-baa4-4e06-803a-ca01f74006a1 id=0x7f0a0401 tag=BaseCommentFragment) …]()
I accessed it through the object themselves by taking the language value

**Comment by Sheikh24608** [comment]
https://media.discordapp.net/attachments/1052936137175470193/1053299213640941598/IMG_20221216_181152_982.jpg
