### ISSUE TITLE
Is this the offical ahlul sunnah quran api? or from the Qadiyani/Ahmadi community?

### ISSUE THREAD

**Issue by spa5k** [fawazahmed0/quran-api#41]
Hey I got some doubt from the comments in README about the Ahmadi community, because non Islamic version should not be there, so before I use it, can you please tell a bit?
And Alhamdulillah on such an excellent work, Mashallah

**Comment by fawazahmed0** [comment]
> Is this the offical ahlul sunnah quran api? or from the Qadiyani/Ahmadi community?

No not from qadiyani community

please feel free to use this API. In case if you find any issue with any of the translation please let me know.

**Comment by spa5k** [comment]
Jazakallah khair bro, thanks for making this awesome api. 👍
