### ISSUE TITLE
Is it possible to differentiate between different types of editions like whether they are of translation/tafsir/translieration or quran text?

### ISSUE THREAD

**Issue by spa5k** [fawazahmed0/quran-api#43]
For example in aquran cloud api, its differentitated correctly - https://api.alquran.cloud/v1/edition

**Comment by fawazahmed0** [comment]
Almost all editions are translations, quran will start with `ara-quran**` and transliterations will be `ara-quran**-la*`

**Comment by spa5k** [comment]
that's quite easy to figure out. Thanks bro 🤗

**Comment by spa5k** [comment]
Are there tafsir's in the editions too? if yes, any way to differentitate them?

**Comment by fawazahmed0** [comment]
No tafsir as far as I know
