### ISSUE TITLE
making collection of api

### ISSUE THREAD

**Issue by Shaeikh** [fawazahmed0/quran-api#44]
AsslamuAlikum

So i am making a collection of apis 
in one api 
i wanna ask if i can use your api as my endpoint which giving your api credits?
Am i allowed to do that?

https://api.islamiq.me
this is the api where it will be shown (the endpoints)

i would be happy and apprieciate if you allow me
Jazak Allah!

**Comment by fawazahmed0** [comment]
yes, you can use

**Comment by fawazahmed0** [comment]
Also there is [hadith-api](https://github.com/fawazahmed0/hadith-api#readme), you can also add that in your api if you like

**Comment by Sheikh24608** [comment]
Jazak Allah Brother, May Allah bless you In-Sha-Allah, I will use both apis

**Comment by Shaeikh** [comment]
ah sorry i was on other account


> Jazak Allah Brother, May Allah bless you In-Sha-Allah, I will use both apis
