### ISSUE TITLE
Adding Edition 

### ISSUE THREAD

**Issue by Shaeikh** [fawazahmed0/quran-api#45]
AsslamuAlikum
Can I give a Edition translated in Urdu by Shaykh ul Islam Dr Muhammad Tahir ul Qadri to contribute this project?

Note: Haven't extracted the data yet, a freind of mine suggested to add that in my discord Bot project which uses this Qur'an Api, i can add it seperately but just asking if you could add that in this api?

Jazak Allah!

**Comment by fawazahmed0** [comment]
> Can I give a Edition translated in Urdu by Shaykh ul Islam Dr Muhammad Tahir ul Qadri to contribute this project?

Yes, please share the translation

**Comment by Shaeikh** [comment]
> > Can I give a Edition translated in Urdu by Shaykh ul Islam Dr Muhammad Tahir ul Qadri to contribute this project?
> 
> Yes, please share the translation

Where can i contact you to give files?
i will upload on Github ofc, but do you have discord ?

**Comment by fawazahmed0** [comment]
No, I don't use discord, you can share the files here

**Comment by Shaeikh** [comment]
> No, I don't use discord, you can share the files here

oh ok, i will upload that here (Discord account got disabled for idk, so I was bit busy setting up new things thats why im responding after 3 days) 
i will upload today In-Sha-Allah

**Comment by Shaeikh** [comment]
AssalamuAlikum!
https://github.com/DRehman-Bilal/Quran-Translation---Tahir-ul-Qadri/blob/master/README.md

**Comment by fawazahmed0** [comment]
could you provide me a text file similar to [this format](https://github.com/fawazahmed0/quran-api/blob/1/database/chapterverse/urd-abulaalamaududi.txt)

**Comment by Shaeikh** [comment]
Sure, but it will take time due to the speed it takes to extract one ayah like 1-2 seconds for one ayah

**Comment by fawazahmed0** [comment]
No problem, take your time

**Comment by Shaeikh** [comment]
AsslamuAlikum!

https://github.com/DRehman-Bilal/Quran-Translation---Tahir-ul-Qadri/blob/master/urd-muhammadtahirulqadri.txt

This is not formatted, i was unable to format due to structure, i didnt extracted them but i use the existing directory with all the files and folders i extracted earlier

**Comment by fawazahmed0** [comment]
There are few mistakes in the text file, for example see [37:23](https://github.com/DRehman-Bilal/Quran-Translation---Tahir-ul-Qadri/blob/28bc630bc792baee51da542780aa6e72a3921191/urd-muhammadtahirulqadri.txt#L3030) and [37:23](https://irfan-ul-quran.com/english/Surah-as-Saffat-with-english-translation/23).

I will try to create a correct text file in my freetime

**Comment by Shaeikh** [comment]
Ok i will see the mistakes and try to format myself

**Comment by Shaeikh** [comment]
Heyy dont format this file cuz it may contains more mistakes, i just saw the folder which contains the verses and its dosent hae any mistake in [37:23](https://github.com/DRehman-Bilal/Quran-Translation---Tahir-ul-Qadri/blob/master/irfan-ul-quran/37/23.json) as u see here

I will make a new formatted file and confirm if it contains any mistakes cuz that will be bad (May Allah forgive me)

**Comment by Shaeikh** [comment]
AsslamuAlikum!

Alhamdullilah i have managed to do it 

https://github.com/DRehman-Bilal/Quran-Translation---Tahir-ul-Qadri/blob/master/urd-muhammadtahirulqadri.txt


Jazak Allah for adding it

**Comment by fawazahmed0** [comment]
[Added](https://cdn.jsdelivr.net/gh/fawazahmed0/quran-api@1/editions/urd-muhammadtahirul.json)
