### ISSUE TITLE
Danish translation is actually Dutch

### ISSUE THREAD

**Issue by 0x1eef** [fawazahmed0/quran-api#48]
The [dan-vandetaal](https://github.com/fawazahmed0/quran-api/tree/1/editions/dan-vandetaal) translation is not Danish but Dutch - as far as I can tell. Should it be stored as `nld-vandetaal` instead ?

**Comment by fawazahmed0** [comment]
Thanks, will take a look.

> Should it be stored as nld-vandetaal instead ?

Yes, I will have to create `nld-vandetaal` while still keeping the `dan-vandetaal` edition

**Comment by 0x1eef** [comment]
Thanks for the quick reply.

> Yes, I will have to create nld-vandetaal while still keeping the dan-vandetaal edition

I understand that makes sense from the perspective of an API version, but it might be misleading to those who assume the language is Danish. Maybe it is a good reason to have v1.1 of the API where the issue can be addressed by removing `dan-vandetaal`.

**Comment by fawazahmed0** [comment]
The translation is available in [nld-unknown](https://cdn.jsdelivr.net/gh/fawazahmed0/quran-api@1/editions/nld-unknown.json). I have [updated the author name](https://github.com/fawazahmed0/quran-api/commit/835d744375ecd84eda3dc4ba2323bfbc2f820d1c) without changing the link

**Comment by 0x1eef** [comment]
Alright :+1: Welcome to close if that resolves it.

**Comment by 0x1eef** [comment]
Hey :wave: I'm looking at my issue list. Can we close this one ?

**Comment by fawazahmed0** [comment]
Jazakallah! for informing
