### ISSUE TITLE
There's mistake in transliteration

### ISSUE THREAD

**Issue by sayyid5416** [fawazahmed0/quran-api#54]
```json
        {
            "chapter": 33,
            "verse": 18,
            "text": "Qad ya'lamul laahul mu'awwiqeena minkum walqaaa'ileena li ikhwaanihim hahumma ilainaa, wa laa yaatoonal baasa illaa qaleelaa"
        },
```

Edition:
```json

    "ara_quran_la1": {
        "name": "ara-quran-la1",
        "author": "Quran Transliteration",
        "language": "Arabic",
        "direction": "ltr",
        "source": "https://quran411.com",
        "comments": "",
        "link": "https://cdn.jsdelivr.net/gh/fawazahmed0/quran-api@1/editions/ara-quran-la1.json",
        "linkmin": "https://cdn.jsdelivr.net/gh/fawazahmed0/quran-api@1/editions/ara-quran-la1.min.json"
    },
```

Mistake:
It should be `halumma` and not `hahumma`. I verified with website: https://quran411.com

**Comment by fawazahmed0** [comment]
Jazakallah, I have corrected [the mistake](https://github.com/fawazahmed0/quran-api/commit/019b4ecd0f27ecbefa2664ea36fcff20c814b017) . It will take sometime for correct data to be visible in api.

**Comment by sayyid5416** [comment]
I'm curious, how did this even occurred? It's not like you could've manually copy pasted those verses. So, Is API using older data or something else?

**Comment by fawazahmed0** [comment]
I scrapped quran411.com in [2020](https://web.archive.org/web/20170331145908/http://quran411.com/surah-ahzab.asp#:~:text=walqaaa%27ileena%20li%20ikhwaanihim-,hahumma,-ilainaa%2C%20wa%20laa)

**Comment by sayyid5416** [comment]
Oh, I see, it was just outdated. 2020 was a long time ago. Thanks for the fix btw.
